name: Verifica snake_case
on:
  pull_request:
    branches: ["main"]

jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Analisa os arquivos 
        run: |
          find . -type f -name "*.py" | while read -r files; do 
              if ! [[ $files =~  ^[a-z]+(_[a-z0-9]+)*\.py$ ]]; then
                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $files esta fora do padrao"
                  exit 1
              fi
          done
        shell: bash 
